version: 0.2

phases:
  pre_build:
    commands:
      - echo "PRE_BUILD phase ..."
      - echo "Updating package list and installing Java 17..."
      - apt-get update
      - apt-get install -y openjdk-17-jdk
      - update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-openjdk-amd64/bin/java 1
      - java -version # Verify Java 17 is installed
      - echo "Installing SonarScanner..."
      - curl -o /opt/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
      - unzip /opt/sonar-scanner.zip -d /opt/
      - export PATH=/opt/sonar-scanner-4.6.2.2472-linux/bin:$PATH
  build:
    commands:
      - echo "Build phase ..."
      - mvn clean verify sonar:sonar -Dsonar.projectKey=project-1 -Dsonar.projectName='project-1' -Dsonar.host.url=http://13.232.93.3:9000 -Dsonar.token=sqp_ccc0954f8810912b6a6fbdfcd016587e931ff77d
      #- sonar-scanner -Dsonar.projectKey=project-1 -Dsonar.sources=. -Dsonar.host.url=http://13.232.93.3:9000 -Dsonar.token=sqp_ccc0954f8810912b6a6fbdfcd016587e931ff77d
  post_build:
    commands:
      - echo "Post build phase ..."
