version: 0.2

phases:
  install:
    commands:
      - echo "Install phase ..."
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo "Pre build phase ..."
      - apt-get update
      - apt-get install -y jq
      - echo "PRE_BUILD phase ..."
      - echo "Installing SonarScanner..."
      - curl -o /opt/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
      - unzip /opt/sonar-scanner.zip -d /opt/
      - export PATH=/opt/sonar-scanner-4.6.2.2472-linux/bin:$PATH
  build:
    commands:
      - echo "Build phase ..."
      - sonar-scanner -Dsonar.projectKey=project-1 -Dsonar.sources=. -Dsonar.host.url=http://13.232.93.3:9000 -Dsonar.token=sqp_ccc0954f8810912b6a6fbdfcd016587e931ff77d
  post_build:
    commands:
      - echo "Post build phase ..."
